DROP TABLE IF EXISTS tests CASCADE;
CREATE TABLE tests (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  deck_id INTEGER REFERENCES decks(id) ON DELETE CASCADE,
  test BOOLEAN DEFAULT false,
  time_start TIMESTAMP,
  time_end TIMESTAMP
);